version: 1.0.{branch}.{build}

clone_depth: 10
shallow_clone: true

# configuration:
#   - Build
#   - Edge
#   - Firefox
#   - Chrome

cache:
  - '%APPDATA%\npm-cache'
  - node_modules
build:
  verbosity: minimal

environment:
  nodejs_version: "11"

deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build

# -
#   matrix:
#     only:
#       - configuration: Edge
#   install:
#     - ps: Install-Product node $env:nodejs_version
#     - npm install
#   build_script:
#     - npm run test:edge -- --single-run
# -
#   matrix:
#     only:
#       - configuration: Firefox
#   install:
#     - ps: Install-Product node $env:nodejs_version
#     - choco install firefox
#     - npm install
#   build_script:
#     - npm run test:firefox -- --single-run
#
# -
#   matrix:
#     only:
#       - configuration: Chrome
#   install:
#     - ps: Install-Product node $env:nodejs_version
#     - choco install googlechrome
#     - npm install
#   build_script:
#     - npm run test:chrome -- --single-run
